/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class CalculadoraVIEW extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraVIEW
     */
    public CalculadoraVIEW() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_titulo = new javax.swing.JLabel();
        txt_n1Soma = new javax.swing.JTextField();
        txt_n2Soma = new javax.swing.JTextField();
        lbl_simboloSoma = new javax.swing.JLabel();
        btn_resultSoma = new javax.swing.JButton();
        lbl_simboloSub = new javax.swing.JLabel();
        btn_resultSubtração = new javax.swing.JButton();
        lbl_Soma = new javax.swing.JLabel();
        lbl_Subtração = new javax.swing.JLabel();
        lbl_Multiplicação = new javax.swing.JLabel();
        txt_n1Multiplicação = new javax.swing.JTextField();
        txt_n2Multiplicação = new javax.swing.JTextField();
        lbl_simboloMulti = new javax.swing.JLabel();
        btn_resultMultiplicação = new javax.swing.JButton();
        lbl_Divisão = new javax.swing.JLabel();
        txt_n1Divisão = new javax.swing.JTextField();
        lbl_simboloDivisão = new javax.swing.JLabel();
        txt_n2Divisão = new javax.swing.JTextField();
        btn_resultDivisão = new javax.swing.JButton();
        lbl_respostaSoma = new javax.swing.JLabel();
        lbl_respostaSub = new javax.swing.JLabel();
        lbl_respostaMulti = new javax.swing.JLabel();
        lbl_respostaDivisão = new javax.swing.JLabel();
        txt_n1Subtração = new javax.swing.JTextField();
        txt_n2Subtração = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_titulo.setText("Cálculos Básicos de Matemática");

        txt_n2Soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_n2SomaActionPerformed(evt);
            }
        });

        lbl_simboloSoma.setText("     +");

        btn_resultSoma.setText("Resultado");
        btn_resultSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resultSomaActionPerformed(evt);
            }
        });

        lbl_simboloSub.setText("     -");

        btn_resultSubtração.setText("Resultado");
        btn_resultSubtração.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resultSubtraçãoActionPerformed(evt);
            }
        });

        lbl_Soma.setText("Soma");

        lbl_Subtração.setText("Subtração");

        lbl_Multiplicação.setText("Multiplicação");

        lbl_simboloMulti.setText("    X");

        btn_resultMultiplicação.setText("Resultado");
        btn_resultMultiplicação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resultMultiplicaçãoActionPerformed(evt);
            }
        });

        lbl_Divisão.setText("Divisão");

        lbl_simboloDivisão.setText("    /");

        btn_resultDivisão.setText("Resultado");
        btn_resultDivisão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resultDivisãoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_n1Divisão, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_simboloDivisão, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_n2Divisão, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Divisão)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_respostaMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(708, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Soma, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Multiplicação)
                            .addComponent(lbl_titulo)
                            .addComponent(lbl_Subtração)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txt_n1Subtração, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lbl_simboloSub, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txt_n2Subtração, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(txt_n1Soma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lbl_simboloSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(txt_n2Soma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(39, 39, 39))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_n1Multiplicação, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_simboloMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_n2Multiplicação, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_resultMultiplicação)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btn_resultSubtração, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_resultSoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_respostaSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_respostaSub, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(lbl_respostaDivisão, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn_resultDivisão))))
                        .addContainerGap(475, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Soma)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_n2Soma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_resultSoma))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_n1Soma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_simboloSoma))
                    .addComponent(lbl_respostaSoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(lbl_Subtração)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_n2Subtração, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_resultSubtração))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_n1Subtração, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_simboloSub))
                    .addComponent(lbl_respostaSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_respostaDivisão, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lbl_Multiplicação)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_n1Multiplicação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_simboloMulti)
                            .addComponent(txt_n2Multiplicação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_resultMultiplicação))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_respostaMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Divisão))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_n1Divisão, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_simboloDivisão)
                            .addComponent(txt_n2Divisão, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_resultDivisão))
                        .addGap(0, 234, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_resultSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resultSomaActionPerformed
        somar();
    }//GEN-LAST:event_btn_resultSomaActionPerformed

    private void btn_resultSubtraçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resultSubtraçãoActionPerformed
        subtração();
    }//GEN-LAST:event_btn_resultSubtraçãoActionPerformed

    private void btn_resultMultiplicaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resultMultiplicaçãoActionPerformed
        multiplicação();
    }//GEN-LAST:event_btn_resultMultiplicaçãoActionPerformed

    private void btn_resultDivisãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resultDivisãoActionPerformed
        divisão();
    }//GEN-LAST:event_btn_resultDivisãoActionPerformed

    private void txt_n2SomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_n2SomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_n2SomaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_resultDivisão;
    private javax.swing.JButton btn_resultMultiplicação;
    private javax.swing.JButton btn_resultSoma;
    private javax.swing.JButton btn_resultSubtração;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_Divisão;
    private javax.swing.JLabel lbl_Multiplicação;
    private javax.swing.JLabel lbl_Soma;
    private javax.swing.JLabel lbl_Subtração;
    private javax.swing.JLabel lbl_respostaDivisão;
    private javax.swing.JLabel lbl_respostaMulti;
    private javax.swing.JLabel lbl_respostaSoma;
    private javax.swing.JLabel lbl_respostaSub;
    private javax.swing.JLabel lbl_simboloDivisão;
    private javax.swing.JLabel lbl_simboloMulti;
    private javax.swing.JLabel lbl_simboloSoma;
    private javax.swing.JLabel lbl_simboloSub;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JTextField txt_n1Divisão;
    private javax.swing.JTextField txt_n1Multiplicação;
    private javax.swing.JTextField txt_n1Soma;
    private javax.swing.JTextField txt_n1Subtração;
    private javax.swing.JTextField txt_n2Divisão;
    private javax.swing.JTextField txt_n2Multiplicação;
    private javax.swing.JTextField txt_n2Soma;
    private javax.swing.JTextField txt_n2Subtração;
    // End of variables declaration//GEN-END:variables

    private void somar(){
        int n1 = Integer.valueOf(txt_n1Soma.getText());
        int n2 = Integer.valueOf(txt_n2Soma.getText());
        int soma = n1 + n2;
        lbl_respostaSoma.setText(String.valueOf(soma));
    }
    
    private void subtração(){
        int n1 = Integer.valueOf(txt_n1Subtração.getText());
        int n2 = Integer.valueOf(txt_n2Subtração.getText());
        int subtração = n1 - n2;
        lbl_respostaSub.setText(String.valueOf(subtração));
    }
    
    private void multiplicação(){
        int n1 = Integer.valueOf(txt_n1Multiplicação.getText());
        int n2 = Integer.valueOf(txt_n2Multiplicação.getText());
        int multiplicação = n1 * n2;
        lbl_respostaMulti.setText(String.valueOf(multiplicação));
    }
    
    private void divisão(){
        int n1 = Integer.valueOf(txt_n1Divisão.getText());
        int n2 = Integer.valueOf(txt_n2Divisão.getText());
        double divisão = 0;
        if(n2 != 0){
            divisão = n1/n2;
        }else{
            JOptionPane.showMessageDialog(this, "Divisao por 0 nao existe!");
        }
        lbl_respostaDivisão.setText(String.valueOf(divisão));
    }
    
    
        
    }    
        
    






